# Generated by Django 5.0.7 on 2024-07-31 09:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=500)),
                ('blog_text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
