# Generated by Django 5.0.7 on 2024-08-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blog_user_alter_blog_created_at_alter_blog_update_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='main_image',
            field=models.ImageField(null=True, upload_to='blogs'),
        ),
    ]
